### PR TITLE
Bump v304

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
😤not sure about what is going on here, some googling around shows that there might be Visual Studio version conflicts...

**Comment by nicoddemus** [comment]
Hmm not immediately at a glance, I'm afraid. 😕 

Perhaps @tadeu can give some insight?

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
Seems like the problem is different now after re-rendering:

```

2022-08-28T20:08:30.7497049Z AutoComplete.cxx
2022-08-28T20:08:30.7923453Z ..\src\AutoComplete.cxx(8): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
2022-08-28T20:08:30.8873165Z NMAKE :  U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE"' : return code '0x2'
2022-08-28T20:08:30.8875493Z Stop.
2022-08-28T20:08:30.8982002Z Skipping axdebug: AXDebug no longer builds on 3.11 and up
2022-08-28T20:08:30.8983400Z Skipping exchdapi: No 64-bit library for utility functions available.
2022-08-28T20:08:30.8984202Z error: can't copy 'build\temp.win-amd64-cpython-310\Release\scintilla\scintilla.dll': doesn't exist or not a regular file
2022-08-28T20:08:30.9680210Z 
```

**Comment by tadeu** [comment]
From [StackOverflow](https://stackoverflow.com/a/65878315):

> In my opinion, the reason is: stdio.h these header files are not located in the path is not in the default path of VS2017, resulting in VS2017 can not find these header files.

> I suggest that you could add the following paths in Properties.

>>    VC++ Directories->Include Directories: C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt

>>    VC++ Directories->Library Directories: C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt\x86

I'm not sure how it worked before, but it looks like it needs a patch to add some include directories (adapted to the current VS and SDK versions, if possible using environment variables such as `UniversalCRTSdkDir` or `VCToolsInstallDir` to be more generic and future-proof).

**Comment by carlodri** [comment]
thanks for you hints @tadeu! Hope I can find some time soon to look into them and try fixing this.

**Comment by carlodri** [comment]
@tadeu I see in the logs that the `ucrt` package is being installed, is this correct? I'm asking since it appears that it should be installed only for Windows < 10 (see [here](https://github.com/conda-forge/ucrt-feedstock)).

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
Sorry to drag you in this @isuruf, but having seen https://github.com/conda-forge/vc-feedstock/pull/38 I was wondering if this could be somehow related. Do you have any insight? Before hand-crafting patches I wanted to ensure that the problem is not upstream in the toolchain.

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by tadeu** [comment]
It does seem related to `ucrt` and `vc`, if `ucrt` is being installed in the build env, perhaps, for a workaround, it's a matter of finding out *where* is this missing header, and adding it "manually" as an include dir.

**Comment by carlodri** [comment]
hmm, works by disabling scintilla. Not sure now disabling this component would affect users....

@conda-forge/pywin32 what is your call on this?

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
the correct folder `C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt` is already in `%INCLUDE%`.... looks like compiler is ignoring it?

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
@conda-forge-admin please rerender

**Comment by carlodri** [comment]
cleaning up the mess and reverting back to the working version without scintilla

will wait for comments for some days and then merge...

**Comment by isuruf** [comment]
This is probably https://github.com/pypa/distutils/issues/174

**Comment by carlodri** [comment]
@conda-forge-admin please rerender
